/**
 * Auto-generated TypeScript types from Rails API
 * Generated on: 2025-06-24T02:21:00.965Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate:types' to regenerate
 */


export enum UserRole {
  CONSUMER = 'consumer',
  SELLER_ADMIN = 'seller_admin',
  SYSTEM_ADMIN = 'system_admin',
}

export interface User {
  id: string;
  email: string;
  first_name: string;
  last_name: string;
  role: UserRole;
  email_verified: boolean;
  avatar?: string;
  phone?: string;
  created_at: string;
  updated_at: string;
  store?: {
    id: string;
    name: string;
    slug: string;
    is_verified: boolean;
    is_active: boolean;
  };
}

export interface AuthResponse {
  user: User;
  token: string;
  message?: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}


export interface Store {
  id: string;
  name: string;
  slug: string;
  description?: string;
  logo?: string;
  banner?: string;
  website?: string;
  is_verified: boolean;
  is_active: boolean;
  commission_rate: number;
  total_sales: number;
  total_orders: number;
  rating?: number;
  review_count: number;
  created_at: string;
  updated_at: string;
  owner: {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
  };
  display_rating: number;
  active: boolean;
  verified: boolean;
}


export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
  image?: string;
  parent_id?: string;
  created_at: string;
  updated_at: string;
  children?: Category[];
  parent?: Category;
}


export enum ProductStatus {
  DRAFT = 0,
  PENDING_APPROVAL = 1,
  ACTIVE = 2,
  INACTIVE = 3,
  REJECTED = 4,
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  short_description?: string;
  base_price: number;
  compare_at_price?: number;
  sku?: string;
  track_inventory: boolean;
  inventory: number;
  low_stock_threshold: number;
  weight?: number;
  dimensions?: string;
  materials?: string[];
  images?: string[];
  videos?: string[];
  meta_title?: string;
  meta_description?: string;
  status: ProductStatus;
  is_featured: boolean;
  store_id: string;
  category_id: string;
  created_at: string;
  updated_at: string;
  store?: Store;
  category?: Category;
}

