app = "indieout-monorepo"
primary_region = "den"
kill_signal = "SIGTERM"

[build]
  dockerfile = "Dockerfile"
  build-args = { VITE_API_URL = "https://indieout-monorepo.fly.dev" }

[deploy]
  release_command = "cd /app/api && bundle exec rails db:migrate"

[env]
  PORT = "80"
  RAILS_ENV = "production"
  NODE_ENV = "production"
  RUN_MIGRATIONS = "false"  # We run migrations in release_command

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "60s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1