apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: indieout
data:
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  FRONTEND_URL: "https://indieout.com"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: indieout
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: indieout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: db-migrate
          image: ghcr.io/yourusername/indieout-api:latest
          command: ["bundle", "exec", "rails", "db:migrate"]
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
      containers:
        - name: api
          image: ghcr.io/yourusername/indieout-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          env:
            - name: DATABASE_URL
              value: "postgresql://indieout:$(POSTGRES_PASSWORD)@postgres:5432/indieout_production"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: indieout
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80