apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: indieout
type: Opaque
stringData:
  password: your-postgres-password-here
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: indieout
type: Opaque
stringData:
  RAILS_MASTER_KEY: your-rails-master-key-here
  JWT_SECRET_KEY: your-jwt-secret-key-here
  AWS_ACCESS_KEY_ID: your-aws-access-key-here
  AWS_SECRET_ACCESS_KEY: your-aws-secret-key-here
  SMTP_PASSWORD: your-smtp-password-here
  STRIPE_SECRET_KEY: your-stripe-secret-key-here
  STRIPE_WEBHOOK_SECRET: your-stripe-webhook-secret-here