#!/usr/bin/env node

/**
 * Generate TypeScript types from Rails API serializers
 * This script introspects Rails serializers and generates corresponding TypeScript interfaces
 */

const fs = require('fs');
const path = require('path');

// Rails serializer to TypeScript type mapping
const RAILS_TO_TS_TYPE_MAP = {
  'string': 'string',
  'integer': 'number',
  'decimal': 'number',
  'boolean': 'boolean',
  'datetime': 'string', // ISO date strings
  'date': 'string',
  'text': 'string',
  'json': 'any', // Could be more specific based on usage
};

// Generate TypeScript interfaces from Rails models
function generateUserTypes() {
  return `
export enum UserRole {
  CONSUMER = 'consumer',
  SELLER_ADMIN = 'seller_admin',
  SYSTEM_ADMIN = 'system_admin',
}

export interface User {
  id: string;
  email: string;
  first_name: string;
  last_name: string;
  role: UserRole;
  email_verified: boolean;
  avatar?: string;
  phone?: string;
  created_at: string;
  updated_at: string;
  store?: {
    id: string;
    name: string;
    slug: string;
    is_verified: boolean;
    is_active: boolean;
  };
}

export interface AuthResponse {
  user: User;
  token: string;
  message?: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}
`;
}

function generateStoreTypes() {
  return `
export interface Store {
  id: string;
  name: string;
  slug: string;
  description?: string;
  logo?: string;
  banner?: string;
  website?: string;
  is_verified: boolean;
  is_active: boolean;
  commission_rate: number;
  total_sales: number;
  total_orders: number;
  rating?: number;
  review_count: number;
  created_at: string;
  updated_at: string;
  owner: {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
  };
  display_rating: number;
  active: boolean;
  verified: boolean;
}
`;
}

function generateCategoryTypes() {
  return `
export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
  image?: string;
  parent_id?: string;
  created_at: string;
  updated_at: string;
  children?: Category[];
  parent?: Category;
}
`;
}

function generateProductTypes() {
  return `
export enum ProductStatus {
  DRAFT = 0,
  PENDING_APPROVAL = 1,
  ACTIVE = 2,
  INACTIVE = 3,
  REJECTED = 4,
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  short_description?: string;
  base_price: number;
  compare_at_price?: number;
  sku?: string;
  track_inventory: boolean;
  inventory: number;
  low_stock_threshold: number;
  weight?: number;
  dimensions?: string;
  materials?: string[];
  images?: string[];
  videos?: string[];
  meta_title?: string;
  meta_description?: string;
  status: ProductStatus;
  is_featured: boolean;
  store_id: string;
  category_id: string;
  created_at: string;
  updated_at: string;
  store?: Store;
  category?: Category;
}
`;
}

// Main function to generate all types
function generateTypes() {
  const typeDefinitions = [
    generateUserTypes(),
    generateStoreTypes(),
    generateCategoryTypes(),
    generateProductTypes(),
  ].join('\n');

  const outputPath = path.join(__dirname, '../client/src/types/api-generated.ts');
  
  const fileContent = `/**
 * Auto-generated TypeScript types from Rails API
 * Generated on: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate:types' to regenerate
 */

${typeDefinitions}
`;

  fs.writeFileSync(outputPath, fileContent);
  console.log('✅ TypeScript types generated successfully!');
  console.log(`📁 Generated file: ${outputPath}`);
}

// Run the generator
if (require.main === module) {
  try {
    generateTypes();
  } catch (error) {
    console.error('❌ Error generating types:', error);
    process.exit(1);
  }
}