FROM ruby:3.2.2

# Install dependencies
RUN apt-get update -qq && \
    apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /rails

# Install bundler
RUN gem install bundler

# Copy Gemfiles
COPY Gemfile Gemfile.lock ./

# Install gems (including development/test gems)
RUN bundle install

# Copy the rest of the app
COPY . .

# Expose port
EXPOSE 3000

# Default command
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]