FROM ruby:3.2.2

# Install dependencies
RUN apt-get update -qq && \
    apt-get install -y \
    build-essential \
    libpq-dev \
    libvips \
    nodejs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /rails

# Install bundler
RUN gem install bundler

# Expose port
EXPOSE 3000

# Default command
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]