name: Deploy to Cloud Run

on:
  push:
    branches: [main] # Adjust based on your branch name

env:
  PROJECT_ID: indieout
  SERVICE_NAME: indieout
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.3'
          bundler-cache: true
          bundler: '1.17.3'

      - name: Run tests
        run: |
          bundle _1.17.3_ install --without development production
          bundle _1.17.3_ exec rake test  # Adjust based on your test framework

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push to Google Container Registry
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:indieout-db \
            --set-env-vars="RAILS_ENV=production,RACK_ENV=production,SECRET_TOKEN=${{ secrets.SECRET_TOKEN }},DB_NAME=indieout_production,DB_USERNAME=indieout-app-user,DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
