name: Deploy Rails to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: indieout
  REGION: us-central1
  SERVICE_NAME: indieout
  REPO_NAME: indieout # Artifact Registry repo

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 ▪︎ Checkout
      - uses: actions/checkout@v4

      # 2 ▪︎ Key-based auth to GCP
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3 ▪︎ gcloud + Docker helper
      - uses: google-github-actions/setup-gcloud@v2

      - name: Authorise Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # 4 ▪︎ Build image
      - name: Create Dockerfile
        run: |
          cat > Dockerfile <<'EOF'
          FROM ruby:3.2-slim

          # OS deps
          RUN apt-get update -qq && \
              apt-get install -y build-essential libpq-dev nodejs git && \
              apt-get clean && rm -rf /var/lib/apt/lists/*

          WORKDIR /app

          # App code
          COPY api/ /app/

          # Bundler config & install
          RUN bundle config set --local path 'vendor/bundle' && \
              bundle config set --local without 'development test' && \
              bundle install

          # Assets
          RUN cp config/database.yml.example config/database.yml || true && \
              bundle exec rake assets:precompile RAILS_ENV=production || true

          ENV RAILS_ENV=production RACK_ENV=production
          EXPOSE 8080
          CMD ["bundle","exec","rails","server","-p","8080","-e","production"]
          EOF

      - name: Build & push image
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"

      # 5 ▪︎ Deploy
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances "$PROJECT_ID:$REGION:indieout-db" \
            --set-env-vars RAILS_ENV=production,RACK_ENV=production,SECRET_TOKEN=${{ secrets.SECRET_TOKEN }},DB_NAME=indieout_production,DB_USERNAME=indieout-app-user,DB_PASSWORD=${{ secrets.DB_PASSWORD }}
