name: Deploy Rails to Cloud Run

# Required GCP Service Account permissions:
# - Cloud Run Admin
# - Service Account User
# - Cloud Build Editor
# - Cloud SQL Client (if using Cloud SQL)

on:
  push:
    branches: [main]

env:
  PROJECT_ID: indieout
  REGION: us-central1
  SERVICE_NAME: indieout

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 ▪︎ Checkout
      - uses: actions/checkout@v4

      # 2 ▪︎ Key-based auth to GCP
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3 ▪︎ gcloud setup
      - uses: google-github-actions/setup-gcloud@v2

      # 4 ▪︎ Create Dockerfile
      - name: Create Dockerfile
        run: |
          cat > Dockerfile <<'EOF'
          FROM ruby:3.3-slim

          # OS deps
          RUN apt-get update -qq && \
              apt-get install -y build-essential libpq-dev nodejs git \
              libyaml-dev libffi-dev && \
              apt-get clean && rm -rf /var/lib/apt/lists/*

          WORKDIR /app

          # App code
          COPY api/ /app/

          # Bundler config & install
          RUN bundle config set --local path 'vendor/bundle' && \
              bundle config set --local without 'development test' && \
              bundle install

          # Assets
          RUN cp config/database.yml.example config/database.yml || true && \
              bundle exec rake assets:precompile RAILS_ENV=production || true

          ENV RAILS_ENV=production RACK_ENV=production
          EXPOSE 8080
          CMD ["bundle","exec","rails","server","-p","8080","-e","production"]
          EOF

      # 5 ▪︎ Deploy using Cloud Build
      - name: Deploy to Cloud Run
        run: |
          # Submit build without streaming logs
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} . --no-user-output-enabled
          
          # Deploy to Cloud Run
          gcloud run deploy "$SERVICE_NAME" \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances "$PROJECT_ID:$REGION:indieout-db" \
            --set-env-vars RAILS_ENV=production,RACK_ENV=production,SECRET_TOKEN=${{ secrets.SECRET_TOKEN }},DB_NAME=indieout_production,DB_USERNAME=indieout-app-user,DB_PASSWORD=${{ secrets.DB_PASSWORD }}
