name: Deploy Rails to Cloud Run

# Required GCP Service Account permissions:
# - Cloud Run Admin
# - Service Account User
# - Cloud Build Editor
# - Cloud SQL Client (if using Cloud SQL)

on:
  push:
    branches: [main]

env:
  PROJECT_ID: indieout
  REGION: us-central1
  SERVICE_NAME: indieout

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 ▪︎ Checkout
      - uses: actions/checkout@v4

      # 2 ▪︎ Key-based auth to GCP
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3 ▪︎ gcloud setup
      - uses: google-github-actions/setup-gcloud@v2

      # 4 ▪︎ Deploy using Cloud Build
      - name: Deploy to Cloud Run
        run: |
          # Submit build without streaming logs
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} . --no-user-output-enabled
          
          # Deploy to Cloud Run
          gcloud run deploy "$SERVICE_NAME" \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --min-instances 0 \
            --max-instances 10 \
            --timeout 60 \
            --add-cloudsql-instances "$PROJECT_ID:$REGION:indieout-db" \
            --set-env-vars RAILS_ENV=production,RACK_ENV=production,RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }},DB_NAME=indieout_production,DB_USERNAME=indieout-app-user,DB_PASSWORD=${{ secrets.DB_PASSWORD }},GCS_BUCKET=${{ secrets.GCS_BUCKET }},GCP_PROJECT_ID=${{ env.PROJECT_ID }}
